/**
 * 마이보드
 */
CREATE TABLE KB_ITEM 
(
	ITEMID			NUMBER (8) NOT NULL, --PK
	USERID			NUMBER (8) NOT NULL, --FK (HR_USER.USERID)
	USER_NAME		VARCHAR2 (1000),
	USER_DISP		VARCHAR2 (1000),
	CONTENT			CLOB,
	STATUS			NUMBER (4),
	ISVISB			NUMBER (1) DEFAULT 0 NOT NULL,
	INST_DATE      	DATE DEFAULT SYSDATE,
	LAST_UPDT       DATE,
	MODULEID NUMBER(8, 0),
	CLASSID NUMBER(8, 0),
	TENANTID NUMBER(4, 0),
	SPID NUMBER(8, 0),
	APPID NUMBER(8, 0)
)
TABLESPACE KANBAN_DAT 
LOGGING;

CREATE TABLE KB_ITEM_CARD 
(
	ITEMID			NUMBER (8) NOT NULL, --FK (KB_ITEM.ITEMID)
	CARDID			NUMBER (8) NOT NULL, --PK
	TITLE			VARCHAR2 (1000),
	CONTENT			VARCHAR2 (4000),
	COLOR			VARCHAR2 (20),
	RGST_USERID		NUMBER (8),
	RGST_NAME		VARCHAR2 (1000),
	RGST_DISP		VARCHAR2 (1000),
	RGST_DATE		DATE DEFAULT SYSDATE,
	ISVISB			NUMBER (1) DEFAULT 0 NOT NULL,
	STATUS			NUMBER (4) DEFAULT - 1 NOT NULL,
	STRT_DATE		DATE,
	END_DATE		DATE,
	FILE_EXT		VARCHAR2 (10),
	FILE_CNT		NUMBER (8) DEFAULT 0 NOT NULL,
	ROW_POINT		VARCHAR2 (100),
	ROW_TITLE		VARCHAR2 (1000),
	COLUMN_POINT	VARCHAR2 (100),
	COLUMN_TITLE	VARCHAR2 (1000),
	SORT			NUMBER (4) DEFAULT 0,
	LAST_UPDT       DATE,
	OPN_CNT			NUMBER (8) DEFAULT 0 NOT NULL,
	ISSEC 			NUMBER(1) DEFAULT 0 NOT NULL
)
TABLESPACE KANBAN_DAT
LOGGING ;

CREATE TABLE KB_ITEM_CARD_FILE
(
	FILEID			NUMBER (8) NOT NULL, --PK
	CARDID			NUMBER (8) NOT NULL,
	GID				NUMBER (8) NOT NULL,
	FILE_NAME		VARCHAR2 (500),
	FILE_SIZE		NUMBER (16) DEFAULT 0 NOT NULL,
	DNLD_CNT		NUMBER (8) DEFAULT 0 NOT NULL,
	SAVE_CODE		NUMBER (4) DEFAULT - 1 NOT NULL,
	SAVE_PATH		VARCHAR2 (500),
	RGST_USERID		NUMBER (8),
	RGST_NAME		VARCHAR2 (1000),
	RGST_DISP		VARCHAR2 (1000),
	VRSN_NUM		NUMBER(8) DEFAULT 1,
	ISLASTVERSION	NUMBER(1) DEFAULT 0,
	INST_DATE		DATE DEFAULT SYSDATE
)
TABLESPACE KANBAN_DAT
LOGGING ;

CREATE TABLE KB_ITEM_CARD_OPN
(
 	OPNID			NUMBER (8) NOT NULL, --PK
	GID				NUMBER (8) NOT NULL,
	CARDID			NUMBER (8) NOT NULL, --FK (KB_ITEM_CARD.CARDID)
	USERID			NUMBER (8),
	USER_NAME		VARCHAR2 (1000),
	USER_DISP		VARCHAR2 (1000),
	RGST_USERID		NUMBER (8),
	RGST_DATE		DATE DEFAULT SYSDATE,
	CONTENT			VARCHAR2 (4000)
)
TABLESPACE KANBAN_DAT 
LOGGING;

CREATE TABLE KB_ITEM_BACKUP
(
ITEMID			NUMBER (8) NOT NULL, --PK
TITLE			VARCHAR2 (1000),
USERID			NUMBER (8) NOT NULL,
USER_NAME		VARCHAR2 (1000),
USER_DISP		VARCHAR2 (1000),
UUID            CLOB,
RGST_DATE		DATE DEFAULT SYSDATE
)
TABLESPACE KANBAN_DAT 
LOGGING;