CREATE SEQUENCE SQ_KB_ITEM INCREMENT BY 1 START WITH 1 ; 
CREATE SEQUENCE SQ_KB_ITEM_CARD INCREMENT BY 1 START WITH 1 ; 
CREATE SEQUENCE SQ_KB_ITEM_CARD_FILE INCREMENT BY 1 START WITH 1 ; 
CREATE SEQUENCE SQ_KB_ITEM_CARD_OPN INCREMENT BY 1 START WITH 1 ; 
CREATE SEQUENCE SQ_KB_ITEM_BACKUP INCREMENT BY 1 START WITH 1 ; 